# Lights
RGB_LIGHT_RED_PIN = 13
RGB_LIGHT_GREEN_PIN = 14
RGB_LIGHT_BLUE_PIN = 15

# Pump
PUMP_DELAY_S = 10
TIME_TO_1DL_MS = 2000
RELAY_PIN = 18
PUMP_BUTTON = 12

# Soil sensor
SOIL_MOISTURE_THRESHOLD = 700
READ_SOIL_INTERVAL_S = 2
SOIL_SDA_PIN = 20
SOIL_SCL_PIN = 21