# Lights
RGB_LIGHT_RED_PIN = 13
RGB_LIGHT_GREEN_PIN = 14
RGB_LIGHT_BLUE_PIN = 15

# Pump
PUMP_DELAY_S = 10
RELAY_PIN = 18
PUMP_BUTTON = 12

# Soil sensor
SOIL_MOISTURE_THRESHOLD = 700
READ_SOIL_INTERVAL_S = 2
SOIL_SDA_PIN = 20
SOIL_SCL_PIN = 21

# DHT sensor
READ_DHT_INTERVAL_S = 2
DHT_PIN = 27

# setting switch
SETTING_SWITCH_SW_PIN = 11
SETTING_SWITCH_CLK_PIN = 7
SETTING_SWITCH_DT_PIN = 10
